# Generated by Django 6.0.4 on 2026-04-22 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_time_string',
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
